certificate:
  warning_days: 45
  critical_days: 15

backup:
  enabled: true
  directory: backups


certificates:
  - name: dms-dev
    path: certs/dev/fullchain.pem

  - name: wms-prod
    path: certs/prod/fullchain.pem
