certificate:
  warning_days: 30
  critical_days: 15

backup:
  enabled: true
  directory: backups
  retention: 3


certificates:
  - name: dms-dev
    path: certs/dev/dms-dev.mpi-apps.co.id
    certbot_name: dms-dev.mpi-apps.co.id
    source_path: certs/dev/dms-dev.mpi-apps.co.id/fullchain.pem

  - name: wms-prod
    path: certs/prod/wms.mpi-apps.co.id
    certbot_name: wms.mpi-apps.co.id
    source_path: certs/prod/wms.mpi-apps.co.id/fullchain.pem

renew:
  enabled: true
  dry_run: true
  timeout: 300
  command: certbot


servers:
  - name: bizhop-dev
    host: 103.82.241.128
    port: 8288
    username: root
    auth:
      type: password
      password_env: exabytes_password
    timeout: 30

  - name: wms-prod
    host: 192.9.166.195
    port: 22
    username: opc
    auth:
      type: key
      private_key: /home/iqbal/ssh/apex.ppk
    timeout: 30


